version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: a123456
    ports:
      - 5432:5432
    volumes:
      - ./examples/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql